version: '3'  

services:
  meals-service:
    build: ./dishes-api  
    restart: always
    volumes:
      - type: bind
        source: ./dishes-api 
        target: /dishes-api 
    environment:
      FLASK_DEBUG: "true"
    depends_on:
    - diets-service

  diets-service:
    build: ./diets-api
    restart: always
    volumes:
      - type: bind
        source: ./diets-api
        target: /diets-api
    environment: 
      FLASK_DEBUG: "true"
    ports:
      - "5002:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  reverse:
    build: ./reverse
    restart: always
    ports:
      - "80:80"
    depends_on:
      - meals-service

  loadbalancer:
    build: ./loadbalancer
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      - meals-service

volumes:
  mongo_data:
