version: '3'  

services:
  dishes-service:
    build: ./dishes-api  
    restart: always
    volumes:
      - type: bind
        source: ./dishes-api 
        target: /dishes-api 
    environment:
      FLASK_DEBUG: "true"
    ports:
      - "8000:8000"
  diets-service:
    build: ./diets-api
    restart: always
    volumes:
      - type: bind
        source: ./diets-api
        target: /diets-api
    environment: 
      FLASK_DEBUG: "true"
    ports:
      - "8001:8000"

  mongo:
      image: mongo
  #    environment:
  #      MONGO_INITDB_ROOT_USERNAME: root
  #      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      ports:
        - 27017:27017
  #    volumes:
  #      - mongo_data:/data/db