version: '3'  

services:
  dishes-service:
    build: ./dishes-api  
    volumes:
      - type: bind
        source: ./dishes-api 
        target: /dishes-api 
    environment:
      FLASK_DEBUG: "true"
    ports:
      - "5001:8000"
  diets-service:
    build: ./diets-api
    volumes:
      - type: bind
        source: ./diets-api
        target: /diets-api
    environment: 
      FLASK_DEBUG: "true"
    ports:
      - "5002:8000"
  reverse:
    build: ./reverse
    ports:
      - "80:80"
    depends_on:
      - dishes-service
      - diets-service