name: Dishes API Unit Tests
run-name: ${{ github.actor }} / ${{ github.event_name }} / ${{ github.sha }}
on: [push]
jobs: 
  unit-tests:
    name: Dishes API Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dishes-api/requirements.txt
      - name: Run unit tests
        run: |
          cd dishes-api && python -m unittest discover -s tests